on:
  push:
    branches: master
  pull_request:
name: CI
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:kde-5.15-25.08
      options: --privileged
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: Restore cache
      id: cache-restore
      uses: actions/cache/restore@v5
      with:
        path: |
          .flatpak-builder
        key: ${{ runner.os }}
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: aegisub.flatpak
        manifest-path: org.aegisub.Aegisub.yml
        cache-key: flatpak-builder-${{ github.sha }}
    - name: Save cache
      id: cache-save
      if: always() && steps.cache-restore.outputs.cache-hit != 'true'
      uses: actions/cache/save@v5
      with:
        path: |
          .flatpak-builder
        key: ${{ steps.cache-restore.outputs.cache-primary-key }}
