on:
  push:
    branches: master
  pull_request:
name: CI
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: Restore cache
      id: cache-restore
      uses: actions/cache/restore@v5
      with:
        path: |
          .flatpak-builder
        key: ${{ runner.os }}
    - name: Install dependencies
      run: |
          sudo apt update
          sudo apt install flatpak flatpak-builder
          flatpak remote-add --user --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
    - name: Build Flatpak
      run: |
          flatpak-builder --force-clean --user --install-deps-from=flathub --repo=repo builddir ./org.aegisub.Aegisub.yml
    - name: Make bundle
      run: flatpak build-bundle repo Aegisub.flatpak org.aegisub.Aegisub --runtime-repo=https://flathub.org/repo/flathub.flatpakrepo
    - name: Upload artifact
      uses: actions/upload-artifact@v7
      with:
        path: Aegisub.flatpak
        archive: false
    - name: Save cache
      id: cache-save
      if: always() && steps.cache-restore.outputs.cache-hit != 'true'
      uses: actions/cache/save@v5
      with:
        path: |
          .flatpak-builder
        key: ${{ steps.cache-restore.outputs.cache-primary-key }}
