on:
  push:
    branches: master
  pull_request:
name: CI
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-50
      options: --privileged
    steps:
    - uses: actions/checkout@v4
    - name: Update submodules
      run: |
          git submodule update --init --recursive
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: palette.flatpak
        manifest-path: org.aegisub.Aegisub.yml
        cache-key: flatpak-builder-${{ github.sha }}
